pipeline {
    agent any

    // environment {
    //     SERVER_CREDS = credentials('ubuntu-cred')
    // }
    
    stages {
        stage('Setup') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'ubuntu-cred', usernameVariable: 'myuser', passwordVariable: 'mypassword')]) {
                    sh '''
                    echo ${myuser}
                    echo ${mypassword}
                    '''
                }
                // echo "my creds: ${SERVER_CREDS}"
                // echo "my user: ${SERVER_CREDS_USR}"
                // echo "my password: ${SERVER_CREDS_PSW}"
                sh "pip install -r 01-jenkins-basics/requirements.txt"            
            }
        }
        stage('Test') {
            steps {
                sh "pytest 01-jenkins-basics/"
            }
        }    
        // stage('Deployment') {
        //     input {
        //         message "Do you want to proceed further?"
        //         ok "Yes"
        //     }
        //     steps {
        //         echo "Running Deployment"      
        //     }
        // }     
    }
}
